.PHONY:clean help list startFlag
clean:
	$(RM) $(OBJECTS)

help:
	$(MAKE) --print-data-base

listVar:
	@echo "$(.VARIABLES)" | tr ' ' '\n' | 	\
	grep -v MAKEF

startFlag:
	@STEP=Begin;	\
	echo -e "$${STEP}\n"

